### ISSUE TITLE
Update please for v1.056. Most of mods not working :(

### ISSUE THREAD

**Issue by wrexwaz** [Albeoris/Trudograd.NuclearEdition#1]
Update please for v1.056. Most of mods not working :(

**Comment by Albeoris** [comment]
@wrexwaz , could you share save and what kind of mod is not working?
I just checked, it seems that everything works fine. Pay attention, you need to turn on some features in config file:
https://github.com/Albeoris/Trudograd.NuclearEdition/wiki/Features

**Comment by vyvexthorne** [comment]
> Update please for v1.056. Most of mods not working :(

For me everything works except dialogue stat check choices. Dialogue skill check choices work fine.  It seems to have a conflict if you try to install other mods using Unity Mod Manager... like the 'No Weight' mod for Atom RPG (which seems fairly popular since it works with Trudograd.)

**Comment by Albeoris** [comment]
> > Update please for v1.056. Most of mods not working :(
> 
> For me everything works except dialogue stat check choices. Dialogue skill check choices work fine. It seems to have a conflict if you try to install other mods using Unity Mod Manager... like the 'No Weight' mod for Atom RPG (which seems fairly popular since it works with Trudograd.)

Hm... what kind of conflict? Could you explain a bit more?

**Comment by Albeoris** [comment]
Feel free to reopen the issue when you will be ready to provide the information. :)
